# Generated by Django 4.2.5 on 2023-09-12 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='box',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_boxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
